# Site settings
title: avayl.net
email: brohken@gmail.com
description: “The personal website for Alex Vayl.”
baseurl: “avayl.net”
url: "http://avayl.net”
twitter_username: alexvayl
github_username:  avayl

# Build settings
markdown: kramdown
permalink: pretty
